Add initial governance vote analysis and CSV report scraping scripts
SetProtocol/index-coop-analytics pull request #25
Opened 2021-04-27 04:19 UTC by craigtutterow

snapshot_report_scraper.py: Uses Selenium to emulate clicks to download CSV reports of governance votes based on provided list of url.

vote_analysis.ipynb: Jupyter notebook containing initial analysis and charts

vote_analysis.py: python executable for analysis code (requires parameter changes for running in local environment)

2021-04-27 20:48 UTC, josephd8 commented
@craigtutterow awesome work. I pulled down your code and got it all running. This is all a great first step. I left a few comments directly in-line on some issues I ran into.

As for next steps, I think there are two levels to this project:
1) delivering a synopsis/report on the takeaways for the Coop regarding governance and voting power - this is to help the Coop have immediate context around the current state of governance/voting power in order to make appropriate decisions to improve governance
2) building tools for continued analysis on governance and voting at the Coop (and possibly beyond the Coop)

I am not sure if I have a vision yet on what we need for #2 to drive the kind of impact needed to make the effort worthwhile, but I want to explore it further. My thoughts are that we use this foundation to really drive some immediate takeways on #1, and then we think about #2 as a more long-term project potentially.

2021-04-27 20:49 UTC, josephd8 requested changes

2021-04-27 20:49 UTC, josephd8 commented on governance/snapshot-vote-analysis/snapshot_report_scraper.py
> +vote_urls = {
I had to remove the keys from this dictionary in order for this to work. It was trying to read the key value as the url.

2021-04-27 20:49 UTC, josephd8 commented on governance/snapshot-vote-analysis/vote_analysis.py
> +    '0xd89c642e52bd9c72bcc0778bcf4de307cc48e75a',
We should also add "0x673d140eed36385cb784e279f8759f495c97cf03" to the list of wallet addresses to exclude for now. I am trying to track down what this contract is, but I am pretty sure it doesn't have voting rights.

2021-04-27 20:49 UTC, josephd8 commented on governance/snapshot-vote-analysis/vote_analysis.py
> +    print(f'Global Wealth Gini Coefficient (2019): 0.885, source: https://en.wikipedia.org/wiki/List_of_countries_by_wealth_inequality')
remove this line

2021-04-27 20:49 UTC, josephd8 commented on governance/snapshot-vote-analysis/vote_analysis.py
> +        minimum_number_of_voters_needed = min(vote_df.index[vote_df['cumulative_dist'] > votes_needed_to_pass]) + 1
`votes_needed_to_pass` is not a known variable

2021-04-27 20:49 UTC, josephd8 commented on governance/snapshot-vote-analysis/vote_analysis.py
> +        quorum_threshold_index = min(vote_df.index[vote_df['cumulative_dist'] > votes_needed_to_pass])
`votes_needed_to_pass` is not a known variable

2021-04-27 23:33 UTC, josephd8 commented
@craigtutterow here are a couple of comments from the Set team on what they are hoping to learn:

- Dylan: "not sure this is in his wheel house, but i'd be curious who isn't voting. we only hit... 25% of circulating tokens or so? I'd be curious where the other 75% are? if they're whales or a long tail?"

- Greg: For each DG2 vote, what % of $INDEX cast was by whales vs. non-whales (building on: https://gov.indexcoop.com/t/iip-voting-analysis/676) . For IIP-7 it was ~80% vs. 20%

2021-05-01 14:52 UTC, craigtutterow commented
Will look into this over the weekend and wrap up by Monday evening. I think the most generically useful and lightweight utility would be a calculator to simulate votes needed to reach quorum and approval rates. We could have an API query that fetches the token distribution, and then inputs/sliders for the various deciles. Also, we could help build the analytics/analysis into Snapshot itself, so it's available as a tab on the vote pages.

2021-05-13 18:33 UTC, josephd8 commented
Hey @craigtutterow just checking in here - any progress? I want to re-iterate that while we have tossed around some cool ideas for tooling, the immediate need here is much simpler - just looking for some answers on the questions brought up by Dylan and Greg (noted a few comments ago) as well as the original questions noted in the issue. A simple pdf report with some visuals, or something like that would suffice!

Let me know, thanks.

2021-05-19 15:13 UTC, merged