TWG - MVI|ETH LP initial liquidity mining
SetProtocol/index-coop-analytics pull request #70
Opened 2021-07-17 14:30 UTC by ripples3

Liquidity mining dashboard for MVI|ETH LP

2021-07-21 05:03 UTC, jackiep00 requested changes
overall looks great! some minor requests around readability and hard-coded values. as a general rule of thumb, we want to be explicit about the meanings of specific values and specific tables for readability and forkability.

Overall logic and structure is great though, this is awesome!

2021-07-21 05:03 UTC, jackiep00 commented on treasury/dune-queries/MVI_Liquidity Mining.sql
> +WHERE minute >= '2021-04-06 00:00'
Add a comment as to why this date was chosen

2021-07-21 05:07 UTC, jackiep00 commented on treasury/dune-queries/MVI_Liquidity Mining.sql
> +lu.balance as "MIST|ETH at UNIv2",
is it MIST or MVI in the column name? coudl be left over code from fork

2021-07-21 07:56 UTC, ripples3 commented on treasury/dune-queries/MVI_Liquidity Mining.sql
> +where "wallet_address" = '\x5bc4249641b4bf4e37ef513f3fa5c63ecab34881'
I added the following as a comment
Wallet / Address
'\x5bc4249641b4bf4e37ef513f3fa5c63ecab34881' - MVI|ETH LP Staking Contract
'\x4d3c5db2c68f6859e0cd05d080979f597dd64bff' - MVI|ETH LP Token 
'\x0954906da0Bf32d5479e25f46056d22f08464cab' - INDEX Token

2021-07-21 08:08 UTC, ripples3 commented on treasury/dune-queries/MVI_Liquidity Mining.sql
> +day, amount as "MVI|ETH LP", amount-amount2 as change
fixed it. Please check the second commit.

2021-07-21 08:08 UTC, ripples3 commented on treasury/dune-queries/MVI_Liquidity Mining.sql
> +from first_day f left join second_day s
fixed it. Please check the second commit.

2021-07-21 08:08 UTC, ripples3 commented on treasury/dune-queries/MVI_Liquidity Mining.sql
> +lu.balance as "MIST|ETH at UNIv2",
fixed it. Please check the second commit.

2021-07-21 15:18 UTC, jackiep00 commented on treasury/dune-queries/MVI-stakers-distribution-behavior.sql
> +temp_table as (
I actually think to answer point 3, the foundation of the query should not be the users who claimed mining rewards, but all of the users that are in the LP.

It might make sense to use the other query you used as a sort of daily INDEX reward rate feed, and window function a sort of "pending INDEX rewards balance" out of it. It feels like what you've written above captures the "claimed INDEX" question and answers part 4

If this is too advanced, I can take a crack at this approach to demo what i'm talking about.

2021-07-26 18:10 UTC, josephd8 commented
@jackiep00 @ripples3 what is the current status of this? Is it live somewhere yet?

2021-07-27 23:10 UTC, jackiep00 commented
> @jackiep00 @ripples3 what is the current status of this? Is it live somewhere yet?

The LP rewards query is available, but haven't socialized the output with the TWG team yet. Other stuff is still under development - aim to get it done by this week

2021-07-29 00:16 UTC, jackiep00 commented
this is ready for merge pending TWG approval tomorrow

2021-08-02 22:41 UTC, merged